/**
 * Phase 6: Patient Registration & Real-Time Device Claim Test Suite
 * Health Tracker — Comprehensive Automated Verification
 *
 * Covers all required test cases:
 *  REGISTRATION:
 *   1. Valid patient registration
 *   2. Missing name rejected
 *   3. Invalid email rejected
 *   4. Duplicate email rejected
 *   5. Password mismatch rejected
 *   6. Invalid password rejected (< 6 chars)
 *   7. Unknown device rejected
 *   8. Inactive device rejected
 *   9. Assigned device rejected
 *  DEVICE CLAIM:
 *  10. Active unassigned device is claimable
 *  11. Successful registration claims device
 *  12. Device.patientId matches Patient.patientId
 *  13. Patient.deviceId matches Device.deviceId
 *  14. Patient cannot claim second device
 *  15. Assigned device cannot be claimed by another patient
 *  16. Inactive device cannot be claimed
 *  17. Reset device becomes claimable
 *  18. Historical telemetry survives reset
 *  SECURITY:
 *  19. Role spoofing rejected (role remains PATIENT)
 *  20. patientId spoofing rejected (patientId generated by server)
 *  21. Doctor cannot self-register through patient registration
 *  22. Client payload cannot inject arbitrary authorization flags
 *  RACE/INTEGRITY:
 *  23. Duplicate simultaneous claim does not create two owners
 *  24. Failed registration does not leave inconsistent ownership
 *  UI/API:
 *  25. Device status endpoint returns CLAIMABLE for active unassigned unit
 *  26. Sensitive fields (apiKeyHash, secrets) are not exposed
 *  27. Validation endpoint handles malformed device IDs safely
 *  28. Status endpoint reflects INACTIVE, ASSIGNED, and UNKNOWN states accurately
 */

require("dotenv").config();
const http = require("http");
const mongoose = require("mongoose");

const app = require("../src/app");
const User = require("../src/models/User");
const Patient = require("../src/models/Patient");
const Doctor = require("../src/models/Doctor");
const Device = require("../src/models/Device");
const SensorReading = require("../src/models/SensorReading");
const ActivityLog = require("../src/models/ActivityLog");
const { ROLES, ACCOUNT_STATUS, DEVICE_STATUS, AUDIT_ACTIONS, TARGET_TYPES } = require("../src/config/constants");
const { hashPassword, generateToken } = require("../src/utils/authUtils");

const TEST_DB_URI = process.env.TEST_MONGODB_URI || "mongodb://127.0.0.1:27017/health_monitoring_phase6_test";

let server;
let baseUrl;
let passedCount = 0;
let failedCount = 0;

function assert(condition, message) {
    if (!condition) {
        throw new Error(message || "Assertion failed");
    }
}

async function runTest(testNumber, testName, fn) {
    try {
        await fn();
        console.log(`[PASS] Test ${testNumber}: ${testName}`);
        passedCount++;
    } catch (err) {
        console.error(`[FAIL] Test ${testNumber}: ${testName}`);
        console.error(`       Error: ${err.message}`);
        failedCount++;
    }
}

// HTTP request helper
async function request(endpoint, options = {}) {
    const url = `${baseUrl}${endpoint}`;
    const headers = options.headers || {};
    if (options.body && !headers["Content-Type"]) {
        headers["Content-Type"] = "application/json";
    }

    const res = await fetch(url, {
        method: options.method || "GET",
        headers,
        body: options.body ? JSON.stringify(options.body) : undefined,
        redirect: options.redirect || "manual"
    });

    const text = await res.text();
    let data;
    try {
        data = JSON.parse(text);
    } catch {
        data = text;
    }

    return {
        status: res.status,
        headers: res.headers,
        data,
        text
    };
}

async function main() {
    console.log("=================================================");
    console.log("RUNNING PHASE 6: PATIENT REGISTRATION & CLAIM TESTS");
    console.log("=================================================\n");

    // 1. Connect to isolated Test MongoDB
    await mongoose.connect(TEST_DB_URI);
    await mongoose.connection.dropDatabase();

    // 2. Start HTTP server on dynamic port
    server = http.createServer(app);
    await new Promise((resolve) => server.listen(0, resolve));
    const port = server.address().port;
    baseUrl = `http://127.0.0.1:${port}`;

    // 3. Seed Base Test Hardware Devices
    await Device.create({
        deviceId: "DEV-P6-001",
        status: DEVICE_STATUS.ACTIVE,
        patientId: null,
        resetCount: 0
    });

    await Device.create({
        deviceId: "DEV-P6-INACTIVE",
        status: DEVICE_STATUS.INACTIVE,
        patientId: null,
        resetCount: 0
    });

    await Device.create({
        deviceId: "DEV-P6-ASSIGNED",
        status: DEVICE_STATUS.ACTIVE,
        patientId: "PAT-EXISTING",
        resetCount: 0
    });

    // Seed Super Admin for reset operations
    const adminHash = await hashPassword("AdminPassword123!");
    const adminUser = await User.create({
        username: "superadmin_p6",
        email: "admin_p6@test.com",
        passwordHash: adminHash,
        role: ROLES.SUPER_ADMIN,
        status: ACCOUNT_STATUS.ACTIVE
    });
    const adminToken = generateToken({
        userId: adminUser._id.toString(),
        role: adminUser.role
    });
    const adminCookie = `token=${adminToken}`;

    // ==========================================
    // SECTION 1: REGISTRATION VALIDATION
    // ==========================================

    // Test 1: Valid patient registration
    let registeredPatientId = null;
    await runTest(1, "Valid patient registration succeeds and returns 201 Created", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "John Doe",
                email: "john_p6@example.com",
                password: "SecurePassword123!",
                confirmPassword: "SecurePassword123!",
                deviceId: "DEV-P6-001",
                age: 32
            }
        });
        assert(res.status === 201, `Expected 201, got ${res.status}`);
        assert(res.data.success === true, "Expected success: true");
        assert(res.data.patient.email === "john_p6@example.com", "Patient email mismatch");
        assert(res.data.patient.deviceId === "DEV-P6-001", "Expected deviceId DEV-P6-001");
        registeredPatientId = res.data.patient.patientId;
    });

    // Test 2: Missing name rejected
    await runTest(2, "Missing name rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "  ",
                email: "missing_name@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-001"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("name is required"), "Expected missing name error message");
    });

    // Test 3: Invalid email rejected
    await runTest(3, "Invalid email format rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Invalid Email User",
                email: "not-a-valid-email",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-001"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("valid email"), "Expected invalid email message");
    });

    // Test 4: Duplicate email rejected
    await runTest(4, "Duplicate email rejected with 400 Bad Request", async () => {
        // Create another active unassigned device
        await Device.create({ deviceId: "DEV-P6-002", status: DEVICE_STATUS.ACTIVE, patientId: null });

        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "John Duplicate",
                email: "john_p6@example.com", // Already registered in Test 1
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-002"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("already registered"), "Expected duplicate email message");
    });

    // Test 5: Password mismatch rejected
    await runTest(5, "Password mismatch rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Mismatch User",
                email: "mismatch@example.com",
                password: "Password123!",
                confirmPassword: "DifferentPassword456!",
                deviceId: "DEV-P6-002"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("do not match"), "Expected passwords mismatch message");
    });

    // Test 6: Invalid password (< 6 chars) rejected
    await runTest(6, "Password shorter than 6 characters rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Short Password User",
                email: "shortpwd@example.com",
                password: "123",
                confirmPassword: "123",
                deviceId: "DEV-P6-002"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("at least 6 characters"), "Expected min length password message");
    });

    // Test 7: Unknown device rejected
    await runTest(7, "Unknown device ID rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Unknown Device User",
                email: "unknown_dev@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-UNKNOWN-999"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("not registered"), "Expected unregistered device message");
    });

    // Test 8: Inactive device rejected
    await runTest(8, "Inactive device rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Inactive Device User",
                email: "inactive_dev@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-INACTIVE"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("not active"), "Expected inactive device message");
    });

    // Test 9: Assigned device rejected
    await runTest(9, "Already assigned device rejected with 400 Bad Request", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Assigned Device User",
                email: "assigned_dev@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-ASSIGNED"
            }
        });
        assert(res.status === 400, `Expected 400, got ${res.status}`);
        assert(res.data.message.includes("already assigned"), "Expected already assigned message");
    });

    // ==========================================
    // SECTION 2: DEVICE CLAIM INVARIANTS
    // ==========================================

    // Test 10: Active unassigned device is claimable
    await runTest(10, "Active unassigned device is claimable via device-status endpoint", async () => {
        const res = await request("/api/auth/device-status/DEV-P6-002");
        assert(res.status === 200, `Expected 200, got ${res.status}`);
        assert(res.data.success === true, "Expected success: true");
        assert(res.data.claimable === true, "Expected claimable: true");
        assert(res.data.status === "CLAIMABLE", "Expected status: CLAIMABLE");
        assert(res.data.message.includes("ready to be assigned"), "Expected ready message");
    });

    // Test 11: Successful registration claims device
    let secondPatientId = null;
    await runTest(11, "Successful registration claims active unassigned device", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Jane Smith",
                email: "jane_p6@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-002",
                age: 29
            }
        });
        assert(res.status === 201, `Expected 201, got ${res.status}`);
        assert(res.data.patient.deviceId === "DEV-P6-002", "Expected claimed deviceId");
        secondPatientId = res.data.patient.patientId;
    });

    // Test 12: Device.patientId matches Patient.patientId
    await runTest(12, "Device.patientId strictly matches Patient.patientId in database", async () => {
        const dev = await Device.findOne({ deviceId: "DEV-P6-002" });
        assert(dev.patientId === secondPatientId, `Expected Device.patientId ${secondPatientId}, got ${dev.patientId}`);
    });

    // Test 13: Patient.deviceId matches Device.deviceId
    await runTest(13, "Patient.deviceId strictly matches Device.deviceId in database", async () => {
        const pat = await Patient.findOne({ patientId: secondPatientId });
        assert(pat.deviceId === "DEV-P6-002", `Expected Patient.deviceId DEV-P6-002, got ${pat.deviceId}`);
    });

    // Test 14: Patient cannot claim second device
    await runTest(14, "Patient cannot claim a second device (1:1 invariant)", async () => {
        // Create another active unassigned device
        await Device.create({ deviceId: "DEV-P6-003", status: DEVICE_STATUS.ACTIVE, patientId: null });

        // Attempt admin assign of second device to Jane Smith
        const res = await request("/api/admin/devices/DEV-P6-003/assign", {
            method: "POST",
            headers: { Cookie: adminCookie },
            body: { patientId: secondPatientId }
        });
        assert(res.status === 400, `Expected 400 Bad Request, got ${res.status}`);
        assert(res.data.message.includes("already assigned to device"), "Expected already assigned error");
    });

    // Test 15: Assigned device cannot be claimed by another patient
    await runTest(15, "Assigned device cannot be claimed by another registration", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Third User",
                email: "third@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-002" // Already claimed by Jane Smith
            }
        });
        assert(res.status === 400, `Expected 400 Bad Request, got ${res.status}`);
        assert(res.data.message.includes("already assigned"), "Expected already assigned message");
    });

    // Test 16: Inactive device cannot be claimed
    await runTest(16, "Inactive device cannot be claimed during registration", async () => {
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Fourth User",
                email: "fourth@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-INACTIVE"
            }
        });
        assert(res.status === 400, `Expected 400 Bad Request, got ${res.status}`);
        assert(res.data.message.includes("not active"), "Expected device not active message");
    });

    // Test 17: Reset device becomes claimable
    await runTest(17, "Reset device becomes claimable for new patient registration", async () => {
        // Ingest telemetry reading for DEV-P6-001 (owned by John Doe)
        await SensorReading.create({
            deviceId: "DEV-P6-001",
            patientId: registeredPatientId,
            doctorId: null,
            value1: 78,
            value2: 98,
            timestamp: new Date()
        });

        // Super Admin resets DEV-P6-001
        const resetRes = await request("/api/admin/devices/DEV-P6-001/reset", {
            method: "POST",
            headers: { Cookie: adminCookie }
        });
        assert(resetRes.status === 200, "Reset must succeed");

        // Verify status endpoint reflects device is now claimable
        const statusRes = await request("/api/auth/device-status/DEV-P6-001");
        assert(statusRes.status === 200, `Expected 200, got ${statusRes.status}`);
        assert(statusRes.data.claimable === true, "Reset device must be claimable");
        assert(statusRes.data.status === "CLAIMABLE", "Expected status CLAIMABLE");

        // Register new patient with reset device
        const regRes = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Fifth User (Post-Reset)",
                email: "fifth_postreset@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-001"
            }
        });
        assert(regRes.status === 201, `Expected 201 Created, got ${regRes.status}`);
        assert(regRes.data.patient.deviceId === "DEV-P6-001", "Expected device successfully reclaimed");
    });

    // Test 18: Historical telemetry survives reset
    await runTest(18, "Historical telemetry records survive device reset untouched", async () => {
        const readings = await SensorReading.find({ deviceId: "DEV-P6-001" });
        assert(readings.length >= 1, `Expected >= 1 reading, got ${readings.length}`);
        assert(readings[0].patientId === registeredPatientId, "Historical patientId must match original owner");
    });

    // ==========================================
    // SECTION 3: SECURITY & SPOOFING DEFENSE
    // ==========================================

    // Test 19: Role spoofing rejected
    await runTest(19, "Role spoofing rejected: client cannot register as SUPER_ADMIN or DOCTOR", async () => {
        await Device.create({ deviceId: "DEV-P6-004", status: DEVICE_STATUS.ACTIVE, patientId: null });

        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Hacker User",
                email: "hacker@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-004",
                role: "SUPER_ADMIN" // Malicious role injection
            }
        });
        assert(res.status === 201, "Registration proceeds but ignores injected role");

        // Verify DB record
        const user = await User.findOne({ email: "hacker@example.com" });
        assert(user.role === ROLES.PATIENT, `Expected role PATIENT, got ${user.role}`);
    });

    // Test 20: patientId spoofing rejected
    await runTest(20, "patientId spoofing rejected: client cannot inject custom patientId", async () => {
        await Device.create({ deviceId: "DEV-P6-005", status: DEVICE_STATUS.ACTIVE, patientId: null });

        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Custom ID User",
                email: "custom_id@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-005",
                patientId: "PAT-HACKED-999" // Malicious patientId injection
            }
        });
        assert(res.status === 201, "Registration succeeds with server-derived ID");
        assert(res.data.patient.patientId !== "PAT-HACKED-999", "Server must ignore client patientId");
        assert(res.data.patient.patientId.startsWith("PAT-"), "Server must issue valid PAT-XXX format");
    });

    // Test 21: Doctor cannot self-register
    await runTest(21, "Doctor self-registration rejected: role is strictly PATIENT", async () => {
        await Device.create({ deviceId: "DEV-P6-006", status: DEVICE_STATUS.ACTIVE, patientId: null });

        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Dr. Wouldbe",
                email: "dr_wouldbe@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-006",
                role: ROLES.DOCTOR
            }
        });
        assert(res.status === 201, "Registration endpoint creates PATIENT account");
        const user = await User.findOne({ email: "dr_wouldbe@example.com" });
        assert(user.role === ROLES.PATIENT, "Account role must remain PATIENT");
    });

    // Test 22: Client payload cannot inject arbitrary authorization flags
    await runTest(22, "Arbitrary authorization flags in client payload are discarded", async () => {
        await Device.create({ deviceId: "DEV-P6-007", status: DEVICE_STATUS.ACTIVE, patientId: null });

        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Flag Injector",
                email: "flag_injector@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-007",
                isAdmin: true,
                isSuperUser: true,
                status: "SUSPENDED"
            }
        });
        assert(res.status === 201, "Registration succeeds normally");
        const user = await User.findOne({ email: "flag_injector@example.com" });
        assert(user.role === ROLES.PATIENT, "Injected isAdmin must have no effect");
        assert(user.status === ACCOUNT_STATUS.ACTIVE, "Injected status must have no effect");
    });

    // ==========================================
    // SECTION 4: RACE CONDITIONS & INTEGRITY
    // ==========================================

    // Test 23: Duplicate simultaneous claim does not create two owners
    await runTest(23, "Duplicate simultaneous claim does not create two owners", async () => {
        // Create an unassigned device
        await Device.create({ deviceId: "DEV-P6-RACE", status: DEVICE_STATUS.ACTIVE, patientId: null });

        // Fire two concurrent registration requests claiming the exact same device
        const p1 = request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Racer 1",
                email: "racer1@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-RACE"
            }
        });

        const p2 = request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Racer 2",
                email: "racer2@example.com",
                password: "Password123!",
                confirmPassword: "Password123!",
                deviceId: "DEV-P6-RACE"
            }
        });

        const [res1, res2] = await Promise.all([p1, p2]);

        const statuses = [res1.status, res2.status].sort();
        // Exactly one must succeed (201) and one must be rejected (400)
        assert(statuses[0] === 201 && statuses[1] === 400, `Expected [201, 400], got [${res1.status}, ${res2.status}]`);

        // Verify in DB that only 1 device document exists and has 1 patient
        const device = await Device.findOne({ deviceId: "DEV-P6-RACE" });
        assert(device.patientId !== null, "Device must be claimed by winner");

        // Verify that only 1 patient owns DEV-P6-RACE
        const owners = await Patient.find({ deviceId: "DEV-P6-RACE" });
        assert(owners.length === 1, `Expected exactly 1 owner, found ${owners.length}`);
    });

    // Test 24: Failed registration does not leave inconsistent ownership
    await runTest(24, "Failed registration does not leave inconsistent ownership", async () => {
        await Device.create({ deviceId: "DEV-P6-FAILTEST", status: DEVICE_STATUS.ACTIVE, patientId: null });

        // Attempt registration with invalid password mismatch
        const res = await request("/api/auth/register", {
            method: "POST",
            body: {
                name: "Failed Reg User",
                email: "failreg@example.com",
                password: "Password123!",
                confirmPassword: "WrongMismatchPassword!",
                deviceId: "DEV-P6-FAILTEST"
            }
        });
        assert(res.status === 400, "Registration must fail on password mismatch");

        // Verify device remains untouched
        const dev = await Device.findOne({ deviceId: "DEV-P6-FAILTEST" });
        assert(dev.patientId === null, "Device must remain unassigned after failed registration");

        // Verify no orphaned Patient or User was created
        const orphanUser = await User.findOne({ email: "failreg@example.com" });
        assert(orphanUser === null, "No User account should be created");
        const orphanPatient = await Patient.findOne({ email: "failreg@example.com" });
        assert(orphanPatient === null, "No Patient record should be created");
    });

    // ==========================================
    // SECTION 5: REAL-TIME DEVICE STATUS API
    // ==========================================

    // Test 25: Device status endpoint returns correct state for active unassigned unit
    await runTest(25, "Device status endpoint returns CLAIMABLE for active unassigned unit", async () => {
        const res = await request("/api/auth/device-status/DEV-P6-FAILTEST");
        assert(res.status === 200, `Expected 200, got ${res.status}`);
        assert(res.data.claimable === true, "Expected claimable true");
        assert(res.data.status === "CLAIMABLE", "Expected status CLAIMABLE");
    });

    // Test 26: Sensitive fields are not exposed in device-status response
    await runTest(26, "Sensitive fields (apiKeyHash, secrets) are not exposed", async () => {
        const res = await request("/api/auth/device-status/DEV-P6-FAILTEST");
        assert(res.data.apiKeyHash === undefined, "apiKeyHash must never be exposed");
        assert(res.data.passwordHash === undefined, "passwordHash must never be exposed");
        assert(res.data._id === undefined || typeof res.data._id === "string", "Internal Mongo internals should not leak unnecessarily");
    });

    // Test 27: Validation endpoint handles malformed device IDs safely
    await runTest(27, "Validation endpoint handles malformed device IDs safely", async () => {
        // Empty / whitespace
        const resEmpty = await request("/api/auth/device-status/%20%20");
        assert(resEmpty.status === 400 || resEmpty.status === 404, `Expected 400/404, got ${resEmpty.status}`);

        // Excessively long device ID
        const longId = "A".repeat(100);
        const resLong = await request(`/api/auth/device-status/${longId}`);
        assert(resLong.status === 400, `Expected 400 for excessive length, got ${resLong.status}`);
    });

    // Test 28: Status endpoint reflects INACTIVE, ASSIGNED, and UNKNOWN states accurately
    await runTest(28, "Status endpoint reflects INACTIVE, ASSIGNED, and UNKNOWN states accurately", async () => {
        // Inactive device
        const resInactive = await request("/api/auth/device-status/DEV-P6-INACTIVE");
        assert(resInactive.status === 200, `Expected 200, got ${resInactive.status}`);
        assert(resInactive.data.claimable === false, "Inactive device must not be claimable");
        assert(resInactive.data.status === "INACTIVE", "Expected status INACTIVE");
        assert(resInactive.data.message.includes("currently inactive"), "Expected inactive message");

        // Assigned device
        const resAssigned = await request("/api/auth/device-status/DEV-P6-ASSIGNED");
        assert(resAssigned.status === 200, `Expected 200, got ${resAssigned.status}`);
        assert(resAssigned.data.claimable === false, "Assigned device must not be claimable");
        assert(resAssigned.data.status === "ASSIGNED", "Expected status ASSIGNED");
        assert(resAssigned.data.message.includes("already assigned"), "Expected assigned message");

        // Unknown device
        const resUnknown = await request("/api/auth/device-status/DEV-DOES-NOT-EXIST");
        assert(resUnknown.status === 404, `Expected 404 for unknown device, got ${resUnknown.status}`);
        assert(resUnknown.data.claimable === false, "Unknown device must not be claimable");
        assert(resUnknown.data.status === "UNKNOWN", "Expected status UNKNOWN");
        assert(resUnknown.data.message.includes("not found"), "Expected not found message");
    });

    // ==========================================
    // CLEANUP & SUMMARY
    // ==========================================
    server.close();
    await mongoose.connection.dropDatabase();
    await mongoose.disconnect();

    console.log("\n=================================================");
    console.log(`TEST SUMMARY: ${passedCount}/28 TESTS PASSED`);
    console.log(`FAILED TESTS: ${failedCount}`);
    console.log("=================================================");

    if (failedCount > 0) {
        console.error("PHASE 6 VERIFICATION: FAILED");
        process.exit(1);
    } else {
        console.log("PHASE 6 VERIFICATION: SUCCESS");
        process.exit(0);
    }
}

main().catch((err) => {
    console.error("FATAL ERROR in Phase 6 test suite:", err);
    process.exit(1);
});
