/**
 * HEALTH TRACKER — SYSTEM CONSTANTS
 * Authoritative Enums and Business Invariants for Data Layer
 */

const ROLES = Object.freeze({
    SUPER_ADMIN: "SUPER_ADMIN",
    DOCTOR: "DOCTOR",
    PATIENT: "PATIENT"
});

const ACCOUNT_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED"
});

const DOCTOR_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
});

const DEVICE_STATUS = Object.freeze({
    ACTIVE: "ACTIVE",
    INACTIVE: "INACTIVE"
});

const TARGET_TYPES = Object.freeze({
    DEVICE: "DEVICE",
    PATIENT: "PATIENT",
    DOCTOR: "DOCTOR",
    USER: "USER",
    SYSTEM: "SYSTEM"
});

const ACTOR_ROLES = Object.freeze({
    SUPER_ADMIN: "SUPER_ADMIN",
    DOCTOR: "DOCTOR",
    PATIENT: "PATIENT",
    SYSTEM: "SYSTEM"
});

const AUDIT_ACTIONS = Object.freeze({
    PATIENT_REGISTERED: "PATIENT_REGISTERED",
    PATIENT_REASSIGNED: "PATIENT_REASSIGNED",
    DOCTOR_CREATED: "DOCTOR_CREATED",
    DOCTOR_STATUS_UPDATED: "DOCTOR_STATUS_UPDATED",
    DOCTOR_REMOVED: "DOCTOR_REMOVED",
    DEVICE_CREATED: "DEVICE_CREATED",
    DEVICE_ACTIVATED: "DEVICE_ACTIVATED",
    DEVICE_DEACTIVATED: "DEVICE_DEACTIVATED",
    DEVICE_ASSIGNED: "DEVICE_ASSIGNED",
    DEVICE_UNASSIGNED: "DEVICE_UNASSIGNED",
    DEVICE_RESET: "DEVICE_RESET",
    DEVICE_DELETED: "DEVICE_DELETED",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    SYSTEM_INIT: "SYSTEM_INIT"
});

module.exports = {
    ROLES,
    ACCOUNT_STATUS,
    DOCTOR_STATUS,
    DEVICE_STATUS,
    TARGET_TYPES,
    ACTOR_ROLES,
    AUDIT_ACTIONS
};
